### ISSUE TITLE
Skip repositories inside other repositories?

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/repocheck#2]
For example AUR4 VCS packages contain a repository in the `src/` directory of the top level package repository, for example `repocheck-git` repository/AUR4 package contains `repocheck-git/src/repocheck`, which is also a git repository. When repocheck is run on a directory with a bunch of AUR4 packages, reports are generated even for the `src/*` repositories, which are either untracked or in `.gitignore`. Since this is not always wanted, an option to skip searching for repositories inside other repositories would be useful.

**Comment by kynikos** [comment]
This should be implemented with the `-n`/`--no-nested-repos` option now, but I haven't tested it very extensively.
